### ISSUE TITLE
Diferent version when building this repo and using the nuget package

### ISSUE THREAD

**Issue by sergioguarino** [vertigoventures/migradoc-extensions#2]
Hi!

I'm checking this project and I see diferent version and functionality when downloading and building the repo
https://github.com/vertigoventures/migradoc-extensions.git -> this is generating version 1.0.1

And when using the nuget package I see the version is 1.1.0.
https://www.nuget.org/packages/MigraDoc.Extensions/

Can I get the code to build version 1.1.0?

Thanks!

**Comment by sergioguarino** [comment]
I'll appreacciate any help on this 
@amirrajan @benfoster @rpmansion 

Thanks!

**Comment by rpmansion** [comment]
@sergioguarino repo is now updated
